version: "3"

services:
  realtime-db:
    image: "rethinkdb:2.4.0"
    container_name: rethinkdb
    restart: always
    ports:
    - 8080:8080
  coinbase-adapter-service:
    depends_on:
      - realtime-db
    environment:
      RETHINK_HOST: ${RETHINK_DB_HOST}
    image: "coinbase-adapter"
    container_name: coinbase_adapter
    restart: always
    ports:
    - 9000:9000
  crypto-analyzer-service:
    depends_on:
      - realtime-db
    image: "crypto-analyzer"
    container_name: crypto_analyzer
    restart: always